# Generated by Django 5.2.8 on 2025-12-24 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        ('scenes', '0001_initial'),
        ('worldbuilding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Timeline', max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timelines', to='notes.novel')),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_label', models.CharField(default='', max_length=100, verbose_name='ช่วงเวลา/ปี')),
                ('order', models.IntegerField(default=0, verbose_name='ลำดับ')),
                ('title', models.CharField(default='', max_length=200, verbose_name='ชื่อเหตุการณ์')),
                ('description', models.TextField(blank=True, default='', verbose_name='รายละเอียดเหตุการณ์')),
                ('image', models.ImageField(blank=True, null=True, upload_to='timeline_events/', verbose_name='รูปภาพเหตุการณ์')),
                ('characters', models.ManyToManyField(blank=True, related_name='timeline_events', to='worldbuilding.character')),
                ('related_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenes.scene', verbose_name='ตรงกับฉาก')),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='timeline.timeline')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
