# Generated by Django 5.2.8 on 2025-12-24 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อเรื่อง')),
                ('synopsis', models.TextField(blank=True, verbose_name='คำโปรย/เรื่องย่อ')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='novel_covers/', verbose_name='รูปปก')),
                ('category', models.CharField(choices=[('FANTASY', 'แฟนตาซี (Fantasy)'), ('BL', 'วาย (Boy Love)'), ('GL', 'ยูริ (Girl Love)'), ('ROMANCE', 'รักโรแมนติก'), ('SCIFI', 'ไซไฟ/อนาคต'), ('ACTION', 'แอคชั่น/กำลังภายใน'), ('HORROR', 'สยองขวัญ/ลึกลับ'), ('FANFIC', 'แฟนฟิคชั่น'), ('OTHER', 'อื่นๆ')], default='OTHER', max_length=20, verbose_name='หมวดหมู่')),
                ('rating', models.CharField(choices=[('G', 'ทั่วไป (General)'), ('PG', 'PG-13 (13+)'), ('R18', 'NC-18 (18+)'), ('R20', 'ฉ20 (20+)')], default='G', max_length=5, verbose_name='ระดับเนื้อหา')),
                ('status', models.CharField(choices=[('ONGOING', 'ยังไม่จบ'), ('COMPLETED', 'จบแล้ว')], default='ONGOING', max_length=10, verbose_name='สถานะเรื่อง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อตอน')),
                ('content', models.TextField(blank=True, verbose_name='เนื้อหา')),
                ('order', models.IntegerField(default=1, verbose_name='ลำดับตอน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='notes.novel')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
