# Generated by Django 5.2.8 on 2025-11-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('project', '📖 โปรเจกต์นิยาย (Project)'), ('idea', '💡 ไอเดียทั่วไป (General Idea)')], default='idea', max_length=20),
        ),
    ]
