# Generated by Django 5.2.8 on 2025-11-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='category',
        ),
    ]
