# Generated by Django 5.2.8 on 2025-11-27 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0002_note_author'),
        ('worldbuilding', '0008_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อฉาก')),
                ('order', models.IntegerField(default=0, verbose_name='ลำดับฉาก')),
                ('status', models.CharField(choices=[('idea', 'Idea (ไอเดียร่าง)'), ('draft', 'Drafting (กำลังเขียน)'), ('revision', 'Revision (รีไรท์)'), ('finished', 'Finished (เสร็จสมบูรณ์)')], default='idea', max_length=20)),
                ('goal', models.TextField(blank=True, help_text='ตัวละครต้องการอะไรในฉากนี้?')),
                ('conflict', models.TextField(blank=True, help_text='อุปสรรคคืออะไร?')),
                ('outcome', models.TextField(blank=True, help_text='ผลลัพธ์เป็นอย่างไร? (ได้/ไม่ได้)')),
                ('content', models.TextField(blank=True, help_text='เนื้อหาฉาก หรือบทร่าง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('characters', models.ManyToManyField(blank=True, related_name='appeared_in_scenes', to='worldbuilding.character')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(blank=True, related_name='used_in_scenes', to='worldbuilding.item')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenes', to='worldbuilding.location')),
                ('pov_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pov_scenes', to='worldbuilding.character')),
                ('project', models.ForeignKey(help_text='ฉากนี้อยู่ในนิยายเรื่องไหน', on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='notes.note')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
