# Generated by Django 5.2.8 on 2025-11-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ชื่อที่ใช้แสดง'),
        ),
    ]
