# Generated by Django 5.2.8 on 2025-12-24 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alias', models.CharField(blank=True, max_length=200)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'ชาย'), ('F', 'หญิง'), ('O', 'อื่นๆ')], max_length=1)),
                ('species', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('appearance', models.TextField(blank=True)),
                ('personality', models.TextField(blank=True)),
                ('background', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='portraits/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_characters', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='notes.novel')),
                ('relationships', models.ManyToManyField(blank=True, related_name='related_to', to='worldbuilding.character')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('world_type', models.CharField(blank=True, help_text='Ex: Fantasy, Sci-Fi, Omegaverse', max_length=100)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='location_maps/')),
                ('terrain', models.TextField(blank=True, help_text='ลักษณะภูมิประเทศ')),
                ('climate', models.TextField(blank=True, help_text='สภาพอากาศ')),
                ('ecosystem', models.TextField(blank=True, help_text='ระบบนิเวศ')),
                ('history', models.TextField(blank=True, help_text='ประวัติศาสตร์ความเป็นมา')),
                ('myths', models.TextField(blank=True, help_text='ตำนานและเรื่องเล่า')),
                ('politics', models.TextField(blank=True, help_text='การปกครอง')),
                ('economy', models.TextField(blank=True, help_text='ระบบเศรษฐกิจ')),
                ('culture', models.TextField(blank=True, help_text='วัฒนธรรม ความเชื่อ ศาสนา')),
                ('language', models.TextField(blank=True, help_text='ภาษาที่ใช้')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='notes.novel')),
                ('residents', models.ManyToManyField(blank=True, related_name='resides_in', to='worldbuilding.character')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('weapon', 'Weapon (อาวุธ)'), ('apparel', 'Apparel/Clothing (เครื่องแต่งกาย)'), ('item', 'Item/Consumable (ไอเทม/ยา)'), ('key_item', 'Key Item/Artifact (วัตถุสำคัญ/อาร์ติแฟกต์)'), ('technology', 'Technology (เทคโนโลยี)'), ('vehicle', 'Vehicle (ยานพาหนะ)'), ('other', 'Other (อื่นๆ)')], default='item', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('abilities', models.TextField(blank=True, help_text='ความสามารถพิเศษ หรือผลของไอเทม')),
                ('limitations', models.TextField(blank=True, help_text='เงื่อนไข ข้อจำกัด หรือผลข้างเคียง')),
                ('appearance', models.TextField(blank=True, help_text='ลักษณะภายนอก วัสดุ สี')),
                ('history', models.TextField(blank=True, help_text='ประวัติความเป็นมา ตำนาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='ผู้ครอบครองปัจจุบัน', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='worldbuilding.character')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='notes.novel')),
                ('location', models.ForeignKey(blank=True, help_text='สถานที่ที่เก็บซ่อนอยู่ (ถ้าไม่มีเจ้าของ)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='worldbuilding.location')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worldbuilding.location'),
        ),
    ]
