# Generated by Django 5.2.8 on 2025-11-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldbuilding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='character',
            name='relationships',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='worldbuilding.character'),
        ),
    ]
