# Generated by Django 5.2.8 on 2025-11-19 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_created_at'),
        ('worldbuilding', '0002_location_alter_character_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='description',
            new_name='appearance',
        ),
        migrations.AddField(
            model_name='character',
            name='alias',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='background',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'ชาย'), ('F', 'หญิง'), ('O', 'อื่นๆ')], max_length=1),
        ),
        migrations.AddField(
            model_name='character',
            name='goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='worldbuilding.location'),
        ),
        migrations.AddField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='personality',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='portrait',
            field=models.ImageField(blank=True, null=True, upload_to='portraits/'),
        ),
        migrations.AddField(
            model_name='character',
            name='role',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='species',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='strengths',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='weaknesses',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='myapp.project'),
        ),
    ]
