# Generated by Django 5.2.8 on 2025-11-25 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_author'),
        ('worldbuilding', '0005_alter_character_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
        migrations.AddField(
            model_name='location',
            name='climate',
            field=models.TextField(blank=True, help_text='สภาพอากาศ'),
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='culture',
            field=models.TextField(blank=True, help_text='วัฒนธรรม ความเชื่อ ศาสนา'),
        ),
        migrations.AddField(
            model_name='location',
            name='economy',
            field=models.TextField(blank=True, help_text='ระบบเศรษฐกิจ'),
        ),
        migrations.AddField(
            model_name='location',
            name='ecosystem',
            field=models.TextField(blank=True, help_text='ระบบนิเวศ'),
        ),
        migrations.AddField(
            model_name='location',
            name='history',
            field=models.TextField(blank=True, help_text='ประวัติศาสตร์ความเป็นมา'),
        ),
        migrations.AddField(
            model_name='location',
            name='language',
            field=models.TextField(blank=True, help_text='ภาษาที่ใช้'),
        ),
        migrations.AddField(
            model_name='location',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='location_maps/'),
        ),
        migrations.AddField(
            model_name='location',
            name='myths',
            field=models.TextField(blank=True, help_text='ตำนานและเรื่องเล่า'),
        ),
        migrations.AddField(
            model_name='location',
            name='politics',
            field=models.TextField(blank=True, help_text='การปกครอง'),
        ),
        migrations.AddField(
            model_name='location',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='notes.note'),
        ),
        migrations.AddField(
            model_name='location',
            name='residents',
            field=models.ManyToManyField(blank=True, related_name='resides_in', to='worldbuilding.character'),
        ),
        migrations.AddField(
            model_name='location',
            name='terrain',
            field=models.TextField(blank=True, help_text='ลักษณะภูมิประเทศ'),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='location',
            name='world_type',
            field=models.CharField(blank=True, help_text='Ex: Fantasy, Sci-Fi, Omegaverse', max_length=100),
        ),
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worldbuilding.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
