# Generated by Django 5.2.8 on 2025-11-26 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_author'),
        ('worldbuilding', '0006_remove_location_description_location_climate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='notes.note'),
        ),
    ]
