# Generated by Django 5.2.8 on 2025-11-27 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_author'),
        ('worldbuilding', '0007_alter_character_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('weapon', 'Weapon (อาวุธ)'), ('apparel', 'Apparel/Clothing (เครื่องแต่งกาย)'), ('item', 'Item/Consumable (ไอเทม/ยา)'), ('key_item', 'Key Item/Artifact (วัตถุสำคัญ/อาร์ติแฟกต์)'), ('technology', 'Technology (เทคโนโลยี)'), ('vehicle', 'Vehicle (ยานพาหนะ)'), ('other', 'Other (อื่นๆ)')], default='item', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('abilities', models.TextField(blank=True, help_text='ความสามารถพิเศษ หรือผลของไอเทม')),
                ('limitations', models.TextField(blank=True, help_text='เงื่อนไข ข้อจำกัด หรือผลข้างเคียง')),
                ('appearance', models.TextField(blank=True, help_text='ลักษณะภายนอก วัสดุ สี')),
                ('history', models.TextField(blank=True, help_text='ประวัติความเป็นมา ตำนาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, help_text='สถานที่ที่เก็บซ่อนอยู่ (ถ้าไม่มีเจ้าของ)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='worldbuilding.location')),
                ('owner', models.ForeignKey(blank=True, help_text='ผู้ครอบครองปัจจุบัน', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory', to='worldbuilding.character')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='notes.note')),
            ],
        ),
    ]
